### Get Stock Details
GET http://localhost:8000/api/v1/stocks/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzU2MzA5MDQwLCJleHAiOjE3NTY3ODkwNDAsIm5iZiI6MTc1NjMwOTA0MCwianRpIjoicmQydVprS2dEYTNScjJIRiIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.oGsw0wxBFQNSl14xfoH_YhPZ4tYOG3QKsKUJDRD_4cw